spring:
  profiles:
    # Mặc định khi chạy dưới máy sẽ dùng 'local'
    # Khi deploy lên server bạn có thể set ENV SPRING_PROFILES_ACTIVE=prod
    active: ${SPRING_PROFILES_ACTIVE}
  jmx:
    enabled: false # Tắt JMX Spring để tiết kiệm RAM

server:
  port: ${PORT:8080}
  servlet:
    context-path: /qlnv-spring

jwt:
  signerKey: ${JWT_KEY}
  valid-duration: 36000 #seconds
  refreshable-duration: 120000 #seconds

security:
  bcrypt-strength: 10
